### PR TITLE
Rafactored tinybird util, new structure, updated README and 

### PR DESCRIPTION
**Pull request by JoeKarlsson**
Added data source to collect final death stats.
Added editor config
Moved files to a better structure, I forgot to use `git mv` so the history got blown up (let me know if you want me to do it right, but I figured it might be fine. 
I also moved the VITE_TOP_10_READ_TOKEN to `.env` you'll need to update that to get it working.

Next Up:
I am going to write some new pipes to make new game stats.

### CODE REVIEW

**Comment by sdairs** [comment]
👍 

Couple notes:
1. Missing the tinybird resources (e.g. the `deaths` Data Source & any new Pipe files)
2. the `scores` events API is now sending the `score` field, which IMO is redundant. It's sending 1 row per point, meaning the score can be calculated by `count() as total, group by session_id`, to get a realtime total scoreboard without storing the incrementing score value from the app. This was a deliberate choice as it can showcase how to use MVs and realtime aggregations (although the MV was not implemented yet). Although the game itself only shows a leaderboard at the end, there could be a companion 'real time leaderboard' that updates as you play.
3. Because of the above, sending the score along with the 'death' event could also be redundant, as we know the total score already. But, there's no harm in this duplication, if anything, it could be an interesting way to compare the individual event counts vs the end-game reported score, for data quality, so happy to leave it in
4. Maybe the `death` event could be expanded with other fields e.g. session start/end time, etc
5. 4. the `.env.example` needs to be updated with the new env var

**Comment by JoeKarlsson** [comment]
Alright - made some updates. Note - I created a turbo token that has access to all the pipes and data sources. It was getting annoying managing so many different tokens. The ENV file should be up to date. 

Also - I am appending the real time stats to the DOM so you can see the data update in realtime. We can make this look pretty once we have some stats locked in.

**Comment by sdairs** [comment]
Nice one 🎉 Looking good

One suggestion would be to keep the implemtation of the realtime leaderboard separate from the implementation of the game.

Perhaps we could move the game to be served on a `/game` route, which is purely just the game, with nothing else around it. Then on the `/` route we create a nice page with the leaderboard and a slot for the game, and just iframe the game into the slot.

The reason behind this ^ is that:
1. it makes it easier to re-use the game in other pages
2. When you use the HTML overlays in Phaser, it gets weird trying to position the HTML container over the game canvas

---

Separtely, the sorting key for the Tinybird DSs are probably not quite right:
1. Scores - I'm not sure `score` should be in the sorting key (I don't think `score` should be a column in this DS at all, actually)
2. Deaths - I don't think `session_id` should be in the sorting key here, as there is only ever 1 death event per sorting key, and the session_ids are just random uuidv4's, so there's no benefit to sorting on them

We should probably look at adding MVs and adjusting the APIs to query the MVs. E.g. there should be an MV that does `count() as score` over the `scores` DS grouping by session id, probably sorting by `score DESC, email` which will be optimised for the leaderboard and scanning scores.

There can be separate MVs to maintan the high level aggregates, e.g. an MV for average score, average score per email, most common score, etc. which can then be queried directly for the result (rather than computing over the raw data each time).

There's an API for avg death per session, which will always be 1, as every death = new session id, see here https://github.com/tinybirdco/flappy-tinybird/pull/4/files#diff-6faf83600c6ed3074ed356b8f0f7becd7e2d7b0c6e521e49703f5eed8ba13db3R28

**Comment by sdairs** [comment]
I'm seeing a bug somewhere that is breaking the leaderboard; it seems like somewhere the Events API calls are being repeated and we are ending up with duplicates

**Comment by JoeKarlsson** [comment]
I'll check it out

**Comment by JoeKarlsson** [comment]
Fixed the bug with game making repeat network calls to tinybird. Should be working fine now. Screenshot 2023-06-16 at 11 47 09 AM

**Comment by JoeKarlsson** [comment]
I think we should get this PR merged, then we can pass it to Dmytro to help work on making this look pretty ✨

**Pull request merged**
